// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJqT9kWHNt34lU74y8WCCIPGWVX0VISE',
    appId: '1:945270049172:android:5bd9085d86a44f27eea781',
    messagingSenderId: '945270049172',
    projectId: 'capsule-7a72b',
    storageBucket: 'capsule-7a72b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJqT9kWHNt34lU74y8WCCIPGWVX0VISE',
    appId: '1:945270049172:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '945270049172',
    projectId: 'capsule-7a72b',
    storageBucket: 'capsule-7a72b.firebasestorage.app',
    iosBundleId: 'com.capsule.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5DAnc9pdHvYhrKyqhU0Eg0o4dTMFBlhE',
    appId: '1:945270049172:web:affb958cabc12a19eea781',
    messagingSenderId: '945270049172',
    projectId: 'capsule-7a72b',
    authDomain: 'capsule-7a72b.firebaseapp.com',
    storageBucket: 'capsule-7a72b.firebasestorage.app',
    measurementId: 'G-Q2QZ62H9H3',
  );
}
